### ISSUE TITLE
Rewrite options combinations

### ISSUE THREAD

**Issue by vincenzobaz** [scalacenter/scala-3-migration-guide#121]
Scala 3 Syntax Rewriting shows these combinations of options.
```
    -indent -old-syntax -rewrite
    -no-indent -old-syntax -rewrite
    -indent -new-syntax -rewrite
    -noindent -new-syntax -rewrite
```
however the indent and syntax flags seem to be mutually exclusive. In my case I use before `-new-syntax -rewrite` and then `-indent -rewrite`.
Using the two at the same time (`-indent -new-syntax -rewrite`) produces
```
[error]   |illegal combination of -rewrite targets: -new-syntax and -indent
```

**Comment by aholland** [comment]
At the time I'm leaving this comment those examples are preceded by the words " In other words, the following combinations of compiler options are not allowed:"

When I read that part yesterday I just looked at the examples and tried them, getting the same error you did. Not a big deal, but I am submitting a pull request on that page, and also updating it to reflect use of the new Scala 3 compiler instead of dotc, and to remind people how to set compile options in an sbt file.
